gridWorkingDir:		workingdir
gridOutputDir:		outputdir_13c_pass4_v2_2run
aliROOTVersion:		v5-09-23-1
aliPhysicsVersion:	vAN-20180222-1
gridDataDir:		/alice/data/2013/LHC13c
dataPattern:		/pass4/*/AliESDs.root
runPrefix:              000
runNumber:		[195677, 195675]
emcalCorrection:	emcal_correction.yaml