gridWorkingDir:		workingdir
gridOutputDir:		outputdir_13f_test_withCorr_latest
aliROOTVersion:		v5-09-23-1
aliPhysicsVersion:      vAN-20180222-1
gridDataDir:		/alice/data/2013/LHC13e
dataPattern:		/pass4/*/AliESDs.root
runPrefix:              000
runNumber:		[196310]
emcalCorrection:	emcal_correction.yaml