gridWorkingDir:         workingdir
gridOutputDir:          outputdir_17g6a1_pthat2_clusterv2_full
aliROOTVersion:         v5-09-11-1
aliPhysicsVersion:      v5-09-11-01-1
gridDataDir:            /alice/sim/2017/LHC17g6a1/2
dataPattern:            */*/AliESDs.root
runPrefix:
runNumber:              [195872, 195867, 195831, 195827, 195826, 195787, 195783]
emcalCorrection:        emcal_correction_forMC.yaml