gridWorkingDir:			workingdir
gridOutputDir:			outputdir_17g6a1_pthat2_1run_v1
aliROOTVersion:			v5-09-23-1
aliPhysicsVersion:		vAN-20180222-1
gridDataDir:			/alice/sim/2017/LHC17g6a1/2
dataPattern:			*/*/AliESDs.root
runPrefix:		
runNumber:			[195872]
emcalCorrection:		emcal_correction_forMC.yaml
emcalGeometryFilename:		geometry_2015.root
emcalLocal2MasterFilename:  	EMCALlocal2master.root