#!/bin/bash

alien_expand() {
    f=$(echo "$1/" | sed "s|//|/|g")
    f_old=""
    while [[ "$f" != "$f_old" ]]; do
	echo "$f" 1>&2
	f_old="$f"
	f=$(while read f; do [[ "${f: -1}" == "/" ]] && \
	    alien_ls -F "$f" | /bin/sed "s|^|$f|" || \
	    echo "$f"; done < <(echo "$f"))
	if echo "$f" | /bin/grep -q \
	    "${tx_dir}/[0-9]\\{3\\}/[0-9]\\{3\\}/"; then
	    echo "$f"
	    break
	fi
    done
}

copy() {
    nproc=0
    for f in $(alien_expand "$1"); do
	case "$f" in
	    $1*/)
		o=$(echo "$f" | /bin/sed "s|.*$1/[0-9]*|$2|")
		if [[ -d "$o" ]]; then
		    echo "info: skipped \
\"alien://${f}AnalysisResults.root\" because output directory \
already exists" 1>&2
		    continue
		fi
		echo "+ alien_cp \
\"alien://${f}AnalysisResults.root\" \"$o\"" 1>&2
		[[ -d "$o" ]] || /bin/mkdir -p "$o"
		alien_cp "alien://${f}AnalysisResults.root" "$o" &
		nproc="$(($nproc + 1))"
		;;
	esac
	[[ "$nproc" -ge "${3:-1}" ]] && wait
	nproc=0
    done
    wait
}

case "$#" in
    2|3)
	copy "$@"
	;;
    *)
	echo "Usage: $0 <source> <destination> [<nprocess>]" 1>&2
	exit 1
	;;
esac
