#!/bin/bash

alien_expand() {
    f=$(echo "$1/" | sed "s|//|/|g")
    f_old=""
    while [[ "$f" != "$f_old" ]]; do
	echo "$f" 1>&2
	f_old="$f"
	f=$(while read f; do [[ "${f: -1}" == "/" ]] && \
	    alien_ls -F "$f" | /bin/sed "s|^|$f|" || \
	    echo "$f"; done < <(echo "$f"))
	if echo "$f" | /bin/grep -q \
	    "${tx_dir}/[0-9]\\{3\\}/[0-9]\\{3\\}/"; then
	    echo "$f"
	    break
	fi
    done
}

copy() {
    for f in $(alien_expand "$1"); do
	case "$f" in
	    *analysis.jdl)
		;;
	    $1*/)
		o=$(echo "$f" | /bin/sed "s|.*$1/\\([0-9]*\\)|$2/\\1|")
		if [[ -f "$o/AnalysisResults.root" ]]; then
		    echo "info: skipped \
\"alien://${f}AnalysisResults.root\" because output file \
\"$o/AnalysisResults.root\" already exists" 1>&2
		    continue
		fi
		while [[ "$nproc" -ge "${3:-1}" ]]; do
		    sleep 2
		    nproc="$(jobs | wc -l)"
		done
		echo "+ alien_cp \
\"alien://${f}AnalysisResults.root\" \"$o\" (nproc = $nproc)" 1>&2
		[[ -d "$o" ]] || /bin/mkdir -p "$o"
		alien_cp "alien://${f}AnalysisResults.root" "$o" &
		nproc="$(jobs | wc -l)"
		;;
	esac
    done
    wait
}

case "$#" in
    2|3)
	copy "$@"
	;;
    *)
	echo "Usage: $0 <source> <destination> [<nprocess>]" 1>&2
	exit 1
	;;
esac
